INSERT
INTO library.countries (name, code)
VALUES ('Afghanistan', 'AFG'),
       ('Albania', 'ALB'),
       ('Algeria', 'DZA'),
       ('Andorra', 'AND'),
       ('Angola', 'AGO'),
       ('Antigua and Barbuda', 'ATG'),
       ('Argentina', 'ARG'),
       ('Armenia', 'ARM'),
       ('Australia', 'AUS'),
       ('Austria', 'AUT'),
       ('Azerbaijan', 'AZE'),
       ('Bahamas', 'BHS'),
       ('Bahrain', 'BHR'),
       ('Bangladesh', 'BGD'),
       ('Barbados', 'BRB'),
       ('Belarus', 'BLR'),
       ('Belgium', 'BEL'),
       ('Belize', 'BLZ'),
       ('Benin', 'BEN'),
       ('Bhutan', 'BTN'),
       ('Bolivia (Plurinational State of)', 'BOL'),
       ('Bosnia and Herzegovina', 'BIH'),
       ('Botswana', 'BWA'),
       ('Brazil', 'BRA'),
       ('Brunei Darussalam', 'BRN'),
       ('Bulgaria', 'BGR'),
       ('Burkina Faso', 'BFA'),
       ('Burundi', 'BDI'),
       ('Cabo Verde', 'CPV'),
       ('Cambodia', 'KHM'),
       ('Cameroon', 'CMR'),
       ('Canada', 'CAN'),
       ('Central African Republic', 'CAF'),
       ('Chad', 'TCD'),
       ('Chile', 'CHL'),
       ('China', 'CHN'),
       ('Colombia', 'COL'),
       ('Comoros', 'COM'),
       ('Congo', 'COG'),
       ('Costa Rica', 'CRI'),
       ('Croatia', 'HRV'),
       ('Cuba', 'CUB'),
       ('Cyprus', 'CYP'),
       ('Czechia', 'CZE'),
       ('Democratic People''s Republic of Korea', 'PRK'),
       ('Democratic Republic of the Congo', 'COD'),
       ('Denmark', 'DNK'),
       ('Djibouti', 'DJI'),
       ('Dominica', 'DMA'),
       ('Dominican Republic', 'DOM'),
       ('Ecuador', 'ECU'),
       ('Egypt', 'EGY'),
       ('El Salvador', 'SLV'),
       ('Equatorial Guinea', 'GNQ'),
       ('Eritrea', 'ERI'),
       ('Estonia', 'EST'),
       ('Eswatini', 'SWZ'),
       ('Ethiopia', 'ETH'),
       ('Fiji', 'FJI'),
       ('Finland', 'FIN'),
       ('France', 'FRA'),
       ('Gabon', 'GAB'),
       ('Gambia', 'GMB'),
       ('Georgia', 'GEO'),
       ('Germany', 'DEU'),
       ('Ghana', 'GHA'),
       ('Greece', 'GRC'),
       ('Grenada', 'GRD'),
       ('Guatemala', 'GTM'),
       ('Guinea', 'GIN'),
       ('Guinea-Bissau', 'GNB'),
       ('Guyana', 'GUY'),
       ('Haiti', 'HTI'),
       ('Honduras', 'HND'),
       ('Hungary', 'HUN'),
       ('Iceland', 'ISL'),
       ('India', 'IND'),
       ('Indonesia', 'IDN'),
       ('Iran (Islamic Republic of)', 'IRN'),
       ('Iraq', 'IRQ'),
       ('Ireland', 'IRL'),
       ('Israel', 'ISR'),
       ('Italy', 'ITA'),
       ('Jamaica', 'JAM'),
       ('Japan', 'JPN'),
       ('Jordan', 'JOR'),
       ('Kazakhstan', 'KAZ'),
       ('Kenya', 'KEN'),
       ('Kiribati', 'KIR'),
       ('Kuwait', 'KWT'),
       ('Kyrgyzstan', 'KGZ'),
       ('Lao People''s Democratic Republic', 'LAO'),
       ('Latvia', 'LVA'),
       ('Lebanon', 'LBN'),
       ('Lesotho', 'LSO'),
       ('Liberia', 'LBR'),
       ('Libya', 'LBY'),
       ('Liechtenstein', 'LIE'),
       ('Lithuania', 'LTU'),
       ('Luxembourg', 'LUX'),
       ('Madagascar', 'MDG'),
       ('Malawi', 'MWI'),
       ('Malaysia', 'MYS'),
       ('Maldives', 'MDV'),
       ('Mali', 'MLI'),
       ('Malta', 'MLT'),
       ('Marshall Islands', 'MHL'),
       ('Mauritania', 'MRT'),
       ('Mauritius', 'MUS'),
       ('Mexico', 'MEX'),
       ('Micronesia (Federated States of)', 'FSM'),
       ('Monaco', 'MCO'),
       ('Mongolia', 'MNG'),
       ('Montenegro', 'MNE'),
       ('Morocco', 'MAR'),
       ('Mozambique', 'MOZ'),
       ('Myanmar', 'MMR'),
       ('Namibia', 'NAM'),
       ('Nauru', 'NRU'),
       ('Nepal', 'NPL'),
       ('Netherlands', 'NLD'),
       ('New Zealand', 'NZL'),
       ('Nicaragua', 'NIC'),
       ('Niger', 'NER'),
       ('Nigeria', 'NGA'),
       ('North Macedonia', 'MKD'),
       ('Norway', 'NOR'),
       ('Oman', 'OMN'),
       ('Pakistan', 'PAK'),
       ('Palau', 'PLW'),
       ('Panama', 'PAN'),
       ('Papua New Guinea', 'PNG'),
       ('Paraguay', 'PRY'),
       ('Peru', 'PER'),
       ('Philippines', 'PHL'),
       ('Poland', 'POL'),
       ('Portugal', 'PRT'),
       ('Qatar', 'QAT'),
       ('Republic of Korea', 'KOR'),
       ('Republic of Moldova', 'MDA'),
       ('Romania', 'ROU'),
       ('Russian Federation', 'RUS'),
       ('Rwanda', 'RWA'),
       ('Saint Kitts and Nevis', 'KNA'),
       ('Saint Lucia', 'LCA'),
       ('Saint Vincent and the Grenadines', 'VCT'),
       ('Samoa', 'WSM'),
       ('San Marino', 'SMR'),
       ('Sao Tome and Principe', 'STP'),
       ('Saudi Arabia', 'SAU'),
       ('Senegal', 'SEN'),
       ('Serbia', 'SRB'),
       ('Seychelles', 'SYC'),
       ('Sierra Leone', 'SLE'),
       ('Singapore', 'SGP'),
       ('Slovakia', 'SVK'),
       ('Slovenia', 'SVN'),
       ('Solomon Islands', 'SLB'),
       ('Somalia', 'SOM'),
       ('South Africa', 'ZAF'),
       ('South Sudan', 'SSD'),
       ('Spain', 'ESP'),
       ('Sri Lanka', 'LKA'),
       ('Sudan', 'SDN'),
       ('Suriname', 'SUR'),
       ('Sweden', 'SWE'),
       ('Switzerland', 'CHE'),
       ('Syrian Arab Republic', 'SYR'),
       ('Tajikistan', 'TJK'),
       ('Thailand', 'THA'),
       ('Timor-Leste', 'TLS'),
       ('Togo', 'TGO'),
       ('Tonga', 'TON'),
       ('Trinidad and Tobago', 'TTO'),
       ('Tunisia', 'TUN'),
       ('Turkey', 'TUR'),
       ('Turkmenistan', 'TKM'),
       ('Tuvalu', 'TUV'),
       ('Uganda', 'UGA'),
       ('Ukraine', 'UKR'),
       ('United Arab Emirates', 'ARE'),
       ('United Kingdom of Great Britain and Northern Ireland', 'GBR'),
       ('United Republic of Tanzania', 'TZA'),
       ('United States of America', 'USA'),
       ('Uruguay', 'URY'),
       ('Uzbekistan', 'UZB'),
       ('Vanuatu', 'VUT'),
       ('Venezuela (Bolivarian Republic of)', 'VEN'),
       ('Viet Nam', 'VNM'),
       ('Western Sahara', 'ESH'),
       ('Yemen', 'YEM'),
       ('Zambia', 'ZMB'),
       ('Zimbabwe', 'ZWE');

INSERT INTO library.addresses (id, country_id, address, zip_code, city)
VALUES (uuid_generate_v4(), (SELECT id FROM library.countries where name = 'Republic of Moldova'), 'Stefan cel Mare Blvd 150', 'MD-2001', 'Chișinău'),
    (uuid_generate_v4(), (SELECT id FROM library.countries where name = 'Republic of Moldova'), 'Independentei Street 12', 'MD-3100', 'Chișinău');

INSERT INTO library.users (id, email, first_name, last_name, address_id)
VALUES (uuid_generate_v4(), 'james.thompson@gmail.com', 'James', 'Thompson',
        (SELECT id FROM library.addresses LIMIT 1)),
    (uuid_generate_v4(), 'olivia.watson@gmail.com', 'Olivia', 'Watson',
     (SELECT id FROM library.addresses OFFSET 1 LIMIT 1));

INSERT INTO library.authors (id, name)
VALUES (uuid_generate_v4(), 'Stephen King'),
       (uuid_generate_v4(), 'Ernest Hemingway'),
       (uuid_generate_v4(), 'Mark Twain');

INSERT INTO library.books (title, author_id, isbn, published_year)
VALUES ('The Shining', (SELECT id FROM library.authors WHERE name = 'Stephen King'), '9780307743657', 1977),
       ('It', (SELECT id FROM library.authors WHERE name = 'Stephen King'), '9781501142970', 1986),
       ('Misery', (SELECT id FROM library.authors WHERE name = 'Stephen King'), '9781501143106', 1987),
       ('11/22/63', (SELECT id FROM library.authors WHERE name = 'Stephen King'), '9781451627299', 2011),
       ('The Old Man and the Sea', (SELECT id FROM library.authors WHERE name = 'Ernest Hemingway'), '9780684801223', 1952),
       ('For Whom the Bell Tolls', (SELECT id FROM library.authors WHERE name = 'Ernest Hemingway'), '9780684803357', 1940),
       ('A Farewell to Arms', (SELECT id FROM library.authors WHERE name = 'Ernest Hemingway'), '9780684801469', 1929),
       ('The Adventures of Tom Sawyer', (SELECT id FROM library.authors WHERE name = 'Mark Twain'), '9780143039563', 1876),
       ('Adventures of Huckleberry Finn', (SELECT id FROM library.authors WHERE name = 'Mark Twain'), '9780486280615', 1884),
       ('The Prince and the Pauper', (SELECT id FROM library.authors WHERE name = 'Mark Twain'), '9780140436693', 1881);
