openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
  description: API for managing users in the library
servers:
  - url: http://localhost:8092

paths:
  /api/users:
    get:
      summary: "GET api/users"
      operationId: "findUsers"
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/UserResponse"
                  totalElements:
                    type: integer
                  totalPages:
                    type: integer
                  number:
                    type: integer
                  size:
                    type: integer

components:
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        addressId:
          type: string
          format: uuid
        active:
          type: boolean
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time

